#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'silex/beluga',
    :git => 'https://github.com/SilexConsulting/puppet-beluga.git'

mod 'puppet/apache',
    :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'

mod 'puppet/concat',
    :git => 'https://github.com/puppetlabs/puppetlabs-concat.git'

#mod 'silex/elda',
#    :git => 'https://github.com/SilexConsulting/puppet-elda.git'

mod 'puppetlabs/firewall',
    :git => 'https://github.com/SilexConsulting/puppetlabs-firewall.git'

mod 'silex/fuseki',
    :git => 'https://github.com/SilexConsulting/puppet-fuseki.git'

mod 'silex/gitlab',
    :git => 'https://github.com/SilexConsulting/puppet-gitlab.git'

mod 'silex/java',
    :git => 'https://github.com/SilexConsulting/puppetlabs-java.git'

mod 'silex/jenkins',
    :git => 'https://github.com/SilexConsulting/puppet-jenkins.git'

mod 'silex/mysql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-mysql.git'

mod 'silex/nginx',
    :git => 'https://github.com/SilexConsulting/puppet-nginx.git'

mod 'puppet/ntp',
   :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'silex/openldap',
    :git => 'https://github.com/SilexConsulting/puppetlabs-openldap.git'

mod 'silex/orgdc',
    :git => 'https://github.com/SilexConsulting/puppet-orgdc.git'

mod 'puppet/stdlib',
    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
    :ref => '4.2.1'

mod 'silex/postgresql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-postgresql'

mod 'silex/referencetimeserver',
    :git => 'https://github.com/SilexConsulting/puppet-referencetimeserver.git'

mod 'silex/solr',
    :git => 'https://github.com/SilexConsulting/puppet-solr.git'

mod 'silex/sudo',
    :git => 'https://github.com/SilexConsulting/puppet-sudo.git'

mod 'silex/tomcat',
    :git => 'https://github.com/SilexConsulting/puppet-tomcat.git'

mod 'silex/varnish',
    :git => 'https://github.com/SilexConsulting/puppet-varnish.git'

mod 'silex/apt',
    :git => 'https://github.com/SilexConsulting/puppetlabs-apt'

mod 'silex/memcached',
    :git => 'https://github.com/SilexConsulting/puppet-memcached'

mod 'silex/nodejs',
    :git => 'https://github.com/SilexConsulting/puppet-nodejs.git'

mod 'silex/composer',
    :git => 'https://github.com/SilexConsulting/puppet-composer.git'

mod 'silex/wget',
    :git => 'https://github.com/SilexConsulting/puppet-wget.git'

mod 'silex/postfix',
    :git => 'https://github.com/SilexConsulting/puppet-postfix.git'

mod 'dgu/dgu_solr',
    :git => 'https://github.com/datagovuk/dgu_solr.git'

mod 'silex/rvm',
    :git => 'https://github.com/SilexConsulting/puppet-rvm.git'

mod 'silex/python',
    :git => 'https://github.com/SilexConsulting/puppet-python.git'

mod 'silex/uwsgi',
    :git => 'https://github.com/SilexConsulting/puppet-uwsgi.git'
